url = "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"

output = "output"

start = 20

duration = 100

# segment = 5

port = 8999

[headers]
User-Agent = "Mozilla/5.0"
Custom-Headers = ["Value1", "Value2"]
