url = "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"

output = "output"

duration = 100

# segment = 5

port = 8999

[headers]
User-Agent = "LocalHls"
Custom-Headers = ["Value1", "Value2"]
