url = "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"

output = "output"

duration = 20

# segment = 5

[headers]
User-Agent = "LocalHls"
Custom-Headers = ["Value1", "Value2"]

[proxy]
url = "http://192.168.1.16"
port = 7890

[server]
port = 8080
